export const countryNames = [
    { id: 1, value: "Afghanistan" },
    { id: 2, value: "Albania" },
    { id: 3, value: "Algeria" },
    { id: 4, value: "American Samoa" },
    { id: 5, value: "Andorra" },
    { id: 6, value: "Angola" },
    { id: 7, value: "Anguilla" },
    { id: 8, value: "Antigua & Barbuda" },
    { id: 9, value: "Argentina" },
    { id: 10, value: "Armenia" },
    { id: 11, value: "Aruba" },
    { id: 12, value: "Australia" },
    { id: 13, value: "Austria" },
    { id: 14, value: "Azerbaijan" },
    { id: 15, value: "Bahamas" },
    { id: 16, value: "Bahrain" },
    { id: 17, value: "Bangladesh" },
    { id: 18, value: "Barbados" },
    { id: 19, value: "Belarus" },
    { id: 20, value: "Belgium" },
    { id: 21, value: "Belize" },
    { id: 22, value: "Benin" },
    { id: 23, value: "Bermuda" },
    { id: 24, value: "Bhutan" },
    { id: 25, value: "Bolivia" },
    { id: 26, value: "Bonaire" },
    { id: 27, value: "Bosnia & Herzegovina" },
    { id: 28, value: "Botswana" },
    { id: 29, value: "Brazil" },
    { id: 30, value: "British Indian Ocean Ter" },
    { id: 31, value: "Brunei" },
    { id: 32, value: "Bulgaria" },
    { id: 33, value: "Burkina Faso" },
    { id: 34, value: "Burundi" },
    { id: 35, value: "Cambodia" },
    { id: 36, value: "Cameroon" },
    { id: 37, value: "Canada" },
    { id: 38, value: "Canary Islands" },
    { id: 39, value: "Cape Verde" },
    { id: 40, value: "Cayman Islands" },
    { id: 41, value: "Central African Republic" },
    { id: 42, value: "Chad" },
    { id: 43, value: "Channel Islands" },
    { id: 44, value: "Chile" },
    { id: 45, value: "China" },
    { id: 46, value: "Christmas Island" },
    { id: 47, value: "Cocos Island" },
    { id: 48, value: "Colombia" },
    { id: 49, value: "Comoros" },
    { id: 50, value: "Congo" },
    { id: 51, value: "Cook Islands" },
    { id: 52, value: "Costa Rica" },
    { id: 53, value: "Cote DIvoire" },
    { id: 54, value: "Croatia" },
    { id: 55, value: "Cuba" },
    { id: 56, value: "Curacao" },
    { id: 57, value: "Cyprus" },
    { id: 58, value: "Czech Republic" },
    { id: 59, value: "Denmark" },
    { id: 60, value: "Djibouti" },
    { id: 61, value: "Dominica" },
    { id: 62, value: "Dominican Republic" },
    { id: 63, value: "East Timor" },
    { id: 64, value: "Ecuador" },
    { id: 65, value: "Egypt" },
    { id: 66, value: "El Salvador" },
    { id: 67, value: "Equatorial Guinea" },
    { id: 68, value: "Eritrea" },
    { id: 69, value: "Estonia" },
    { id: 70, value: "Ethiopia" },
    { id: 71, value: "Falkland Islands" },
    { id: 72, value: "Faroe Islands" },
    { id: 73, value: "Fiji" },
    { id: 74, value: "Finland" },
    { id: 75, value: "France" },
    { id: 76, value: "French Guiana" },
    { id: 77, value: "French Polynesia" },
    { id: 78, value: "French Southern Ter" },
    { id: 79, value: "Gabon" },
    { id: 80, value: "Gambia" },
    { id: 81, value: "Georgia" },
    { id: 82, value: "Germany" },
    { id: 83, value: "Ghana" },
    { id: 84, value: "Gibraltar" },
    { id: 85, value: "Great Britain" },
    { id: 86, value: "Greece" },
    { id: 87, value: "Greenland" },
    { id: 88, value: "Grenada" },
    { id: 89, value: "Guadeloupe" },
    { id: 90, value: "Guam" },
    { id: 91, value: "Guatemala" },
    { id: 92, value: "Guinea" },
    { id: 93, value: "Guyana" },
    { id: 94, value: "Haiti" },
    { id: 95, value: "Hawaii" },
    { id: 96, value: "Honduras" },
    { id: 97, value: "Hong Kong" },
    { id: 98, value: "Hungary" },
    { id: 99, value: "Iceland" },
    { id: 100, value: "Indonesia" },
    { id: 101, value: "India" },
    { id: 102, value: "Iran" },
    { id: 103, value: "Iraq" },
    { id: 104, value: "Ireland" },
    { id: 105, value: "Isle of Man" },
    { id: 106, value: "Israel" },
    { id: 107, value: "Italy" },
    { id: 108, value: "Jamaica" },
    { id: 109, value: "Japan" },
    { id: 110, value: "Jordan" },
    { id: 111, value: "Kazakhstan" },
    { id: 112, value: "Kenya" },
    { id: 113, value: "Kiribati" },
    { id: 114, value: "Korea North" },
    { id: 115, value: "Korea South" },
    { id: 116, value: "Kuwait" },
    { id: 117, value: "Kyrgyzstan" },
    { id: 118, value: "Laos" },
    { id: 119, value: "Latvia" },
    { id: 120, value: "Lebanon" },
    { id: 121, value: "Lesotho" },
    { id: 122, value: "Liberia" },
    { id: 123, value: "Libya" },
    { id: 124, value: "Liechtenstein" },
    { id: 125, value: "Lithuania" },
    { id: 126, value: "Luxembourg" },
    { id: 127, value: "Macau" },
    { id: 128, value: "Macedonia" },
    { id: 129, value: "Madagascar" },
    { id: 130, value: "Malaysia" },
    { id: 131, value: "Malawi" },
    { id: 132, value: "Maldives" },
    { id: 133, value: "Mali" },
    { id: 134, value: "Malta" },
    { id: 135, value: "Marshall Islands" },
    { id: 136, value: "Martinique" },
    { id: 137, value: "Mauritania" },
    { id: 138, value: "Mauritius" },
    { id: 139, value: "Mexico" },
    { id: 140, value: "Midway Islands" },
    { id: 141, value: "Moldova" },
    { id: 142, value: "Monaco" },
    { id: 143, value: "Mongolia" },
    { id: 144, value: "Montserrat" },
    { id: 145, value: "Morocco" },
    { id: 146, value: "Mozambique" },
    { id: 147, value: "Myanmar" },
    { id: 148, value: "Nambia" },
    { id: 149, value: "Nauru" },
    { id: 150, value: "Nepal" },
    { id: 151, value: "Netherland Antilles" },
    { id: 152, value: "Netherlands" },
    { id: 153, value: "Nevis" },
    { id: 154, value: "New Caledonia" },
    { id: 155, value: "New Zealand" },
    { id: 156, value: "Nicaragua" },
    { id: 157, value: "Niger" },
    { id: 158, value: "Nigeria" },
    { id: 159, value: "Niue" },
    { id: 160, value: "Norfolk Island" },
    { id: 161, value: "Norway" },
    { id: 162, value: "Oman" },
    { id: 163, value: "Pakistan" },
    { id: 164, value: "Palau Island" },
    { id: 165, value: "Palestine" },
    { id: 166, value: "Panama" },
    { id: 167, value: "Papua New Guinea" },
    { id: 168, value: "Paraguay" },
    { id: 169, value: "Peru" },
    { id: 170, value: "Philippines" },
    { id: 171, value: "Pitcairn Island" },
    { id: 172, value: "Poland" },
    { id: 173, value: "Portugal" },
    { id: 174, value: "Puerto Rico" },
    { id: 175, value: "Qatar" },
    { id: 176, value: "Republic of Montenegro" },
    { id: 177, value: "Republic of Serbia" },
    { id: 178, value: "Reunion" },
    { id: 179, value: "Romania" },
    { id: 180, value: "Russia" },
    { id: 181, value: "Rwanda" },
    { id: 182, value: "St Barthelemy" },
    { id: 183, value: "St Eustatius" },
    { id: 184, value: "St Helena" },
    { id: 185, value: "St Kitts - Nevis" },
    { id: 186, value: "St Lucia" },
    { id: 187, value: "St Maarten" },
    { id: 188, value: "St Pierre & Miquelon" },
    { id: 189, value: "St Vincent & Grenadines" },
    { id: 190, value: "Saipan" },
    { id: 191, value: "Samoa" },
    { id: 192, value: "Samoa American" },
    { id: 193, value: "San Marino" },
    { id: 194, value: "Sao Tome & Principe" },
    { id: 195, value: "Saudi Arabia" },
    { id: 196, value: "Senegal" },
    { id: 197, value: "Seychelles" },
    { id: 198, value: "Sierra Leone" },
    { id: 199, value: "Singapore" },
    { id: 200, value: "Slovakia" },
    { id: 201, value: "Slovenia" },
    { id: 202, value: "Solomon Islands" },
    { id: 203, value: "Somalia" },
    { id: 204, value: "South Africa" },
    { id: 205, value: "Spain" },
    { id: 206, value: "Sri Lanka" },
    { id: 207, value: "Sudan" },
    { id: 208, value: "Suriname" },
    { id: 209, value: "Swaziland" },
    { id: 210, value: "Sweden" },
    { id: 211, value: "Switzerland" },
    { id: 212, value: "Syria" },
    { id: 213, value: "Tahiti" },
    { id: 214, value: "Taiwan" },
    { id: 215, value: "Tajikistan" },
    { id: 216, value: "Tanzania" },
    { id: 217, value: "Thailand" },
    { id: 218, value: "Togo" },
    { id: 219, value: "Tokelau" },
    { id: 220, value: "Tonga" },
    { id: 221, value: "Trinidad & Tobago" },
    { id: 222, value: "Tunisia" },
    { id: 223, value: "Turkey" },
    { id: 224, value: "Turkmenistan" },
    { id: 225, value: "Turks & Caicos Is" },
    { id: 226, value: "Tuvalu" },
    { id: 227, value: "Uganda" },
    { id: 228, value: "United Kingdom" },
    { id: 229, value: "Ukraine" },
    { id: 230, value: "United Arab Emirates" },
    { id: 231, value: "United States" },
    { id: 232, value: "Uruguay" },
    { id: 233, value: "Uzbekistan" },
    { id: 234, value: "Vanuatu" },
    { id: 235, value: "Vatican City State" },
    { id: 236, value: "Venezuela" },
    { id: 237, value: "Vietnam" },
    { id: 238, value: "Virgin Islands(Brit)" },
    { id: 239, value: "Virgin Islands(USA)" },
    { id: 240, value: "Wake Island" },
    { id: 241, value: "Wallis & Futana Is" },
    { id: 242, value: "Yemen" },
    { id: 243, value: "Zaire" },
    { id: 244, value: "Zambia" },
    { id: 245, value: "Zimbabwe" }
];